version: "3.6"

services:
  app:
    image: ${APP_NAME}
    container_name: ${APP_NAME}
    ports:
      - 3000:3000
    restart: always
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15.1
    container_name: ${APP_NAME}_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:5432

volumes:
  node_modules:
  postgres:
