version: "3.6"

services:
  app:
    image: ${APP_NAME}
    container_name: ${APP_NAME}
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
